test branch
kate-ka/cats_frontend pull request #1
Opened 2016-11-10 18:10 UTC by kate-ka

2016-11-10 18:11 UTC, kate-ka commented on .gitignore
> +/.idea/workspace.xml
please add new line

2016-11-11 16:45 UTC, metalpriest commented
Good job, but please do fixes according comments

2016-11-11 17:21 UTC, metalpriest requested changes

2016-11-11 17:21 UTC, metalpriest commented on app/scripts/controllers/articles.js
> +  .controller('ArticlesCtrl', ['pages',function (carousel_pages) {
Better to rename to mainPageCtrl or homePageCtrl as it could contains not only articles

2016-11-11 17:21 UTC, metalpriest commented on app/scripts/controllers/articles.js
> +        vm.items = [];
Rename it to caruselPages please

2016-11-11 17:21 UTC, metalpriest commented on app/scripts/controllers/articles.js
> +  .controller('ArticlesCtrl', ['pages',function (pages) {
Pkease rename conroller ArticlesCtrl to MainPageCtrl

2016-11-11 17:21 UTC, metalpriest commented on app/scripts/controllers/articles.js
> +        vm.items = [];
Please rename it to articles

2016-11-12 11:21 UTC, merged